# Generated by Django 4.2.7 on 2023-11-25 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tdlist', '0002_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
